language: php

php:
  - 5.6

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - vendor/bin/kahlan

notifications:
    email: false
